### ISSUE TITLE
ran per install instructions typed motivate and got this error

### ISSUE THREAD

**Issue by staycreativedesign** [mubaris/motivate#2]
Traceback (most recent call last):
  File "/Users/admin/.motivate/motivate", line 11, in <module>
    rand_no = random.randint(1, num_of_json)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/random.py", line 220, in randint
    return self.randrange(a, b+1)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/random.py", line 198, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (1,1, 0)

**Comment by mubaris** [comment]
Which python version are you using?

**Comment by staycreativedesign** [comment]
damnit... 2.7 stupid

**Comment by staycreativedesign** [comment]
well im on mac os sierra and it has the latest python and python3

**Comment by staycreativedesign** [comment]
found it... its not copying the files inside data ...

`[~/motivate/data]$ cp *.* ~/.motivate/data `

and it works
